/**
 * Labelled DEMO_SYNTHETIC CeX boxes for tests and the demo UI.
 * These are NOT live CeX inventory. Never treat them as current store stock.
 */

import type { CexBox } from './types.ts';

export const DEMO_CEX_BOXES: CexBox[] = [
  {
    boxId: 'demo-rx6600-1',
    boxName: 'AMD Radeon RX 6600 8GB GDDR6 PCI-E Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 105,
    cashPrice: 65,
    exchangePrice: 72,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 3,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-rtx3060-12',
    boxName: 'NVIDIA GeForce RTX 3060 12GB GDDR6 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 149,
    cashPrice: 95,
    exchangePrice: 105,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 1,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-rtx3060-8',
    boxName: 'NVIDIA GeForce RTX 3060 8GB GDDR6 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 129,
    cashPrice: 82,
    exchangePrice: 90,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 2,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-gtx1660s',
    boxName: 'MSI GeForce GTX 1660 Super 6GB GDDR6 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 89,
    cashPrice: 58,
    exchangePrice: 64,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 4,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-gtx1080',
    boxName: 'ASUS ROG Strix GeForce GTX 1080 8GB GDDR5X Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 99,
    cashPrice: 64,
    exchangePrice: 70,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 1,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-rtx3060ti',
    boxName: 'Gigabyte GeForce RTX 3060 Ti 8GB GDDR6 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 179,
    cashPrice: 120,
    exchangePrice: 132,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 1,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-rx580',
    boxName: 'Sapphire Radeon RX 580 8GB GDDR5 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 55,
    cashPrice: 32,
    exchangePrice: 38,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 6,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-rx6600xt',
    boxName: 'ASUS Radeon RX 6600 XT 8GB GDDR6 Graphics Card',
    categoryId: 892,
    categoryName: 'PCI-E Graphics Cards',
    superCatName: 'Computing',
    sellPrice: 135,
    cashPrice: 92,
    exchangePrice: 100,
    outOfStock: true,
    outOfEcomStock: true,
    ecomQuantityOnHand: 0,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
  {
    boxId: 'demo-r5-3600',
    boxName: 'AMD Ryzen 5 3600 Hexa-Core Processor',
    categoryId: 910,
    categoryName: 'AMD Desktop CPUs',
    superCatName: 'Computing',
    sellPrice: 42,
    cashPrice: 26,
    exchangePrice: 30,
    outOfStock: false,
    outOfEcomStock: false,
    ecomQuantityOnHand: 8,
    imageLarge: null,
    imageMedium: null,
    cannotBuy: false,
  },
];

export const DEMO_CEX_BOXES_RESPONSE = {
  response: {
    ack: 'Success' as const,
    data: {
      boxes: DEMO_CEX_BOXES.map((b) => ({
        boxId: b.boxId,
        boxName: b.boxName,
        categoryId: b.categoryId,
        categoryName: b.categoryName,
        superCatName: b.superCatName,
        sellPrice: b.sellPrice,
        cashPrice: b.cashPrice,
        exchangePrice: b.exchangePrice,
        outOfStock: b.outOfStock ? 1 : 0,
        outOfEcomStock: b.outOfEcomStock ? 1 : 0,
        ecomQuantityOnHand: b.ecomQuantityOnHand,
        cannotBuy: b.cannotBuy ? 1 : 0,
        imageUrls: { large: b.imageLarge, medium: b.imageMedium },
      })),
      totalBoxes: DEMO_CEX_BOXES.length,
      firstRecord: 1,
      count: DEMO_CEX_BOXES.length,
    },
  },
};
